# Read Product Hunt GraphQL API for my upvotes and post them to my site

on:
  poll:
    url: https://api.producthunt.com/v2/api/graphql
    itemsPath: data.viewer.user.votedPosts.edges
    deduplicationKey: node.id
    requestConfig:
      method: POST
      data:
        query: "{ viewer { user { votedPosts { edges { node { id createdAt description website url thumbnail { type url videoUrl } tagline name } } } } } }"
      headers:
        Authorization: Bearer ${{ secrets.PRODUCTHUNT_TOKEN }}

jobs:
  publish:
    name: "Publish to grant.codes"
    runs-on: ubuntu-latest
    steps:
      - uses: grantcodes/micropub-action@v1
        with:
          endpoint: ${{ secrets.MICROPUB_ENDPOINT }}
          token: ${{ secrets.MICROPUB_TOKEN }}
          post:
            like-of: ${{ on.poll.outputs.node.website }}
            summary: Liked ${{ on.poll.outputs.node.name }} on Product Hunt
            syndication: ${{ on.poll.outputs.node.url }}
