# Read Reddit json for my upvotes and post them to my site.
# Get the url from https://www.reddit.com/prefs/feeds/

on:
  rss:
    url: ${{ secrets.REDDIT_UPVOTED_RSS }}
    config:
      debug: true
      limit: 10
      skipFirst: true
      # every: 60
jobs:
  # publish:
  #   name: "Publish to grant.codes"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: grantcodes/micropub-action@v1
  #       with:
  #         endpoint: ${{ secrets.MICROPUB_ENDPOINT }}
  #         token: ${{ secrets.MICROPUB_TOKEN }}
  #         post: |
  #           {
  #             "like-of": "${{ on.poll.outputs.url }}",
  #             "summary": "Liked ${{ on.poll.outputs.title }} on Reddit",
  #             "syndication": "https://reddit.com${{ on.poll.outputs.permalink }}"
  #           }
  print:
    name: Test Print
    runs-on: ubuntu-latest
    steps:
      - name: Test Print
        env:
          title: ${{ on.poll.outputs.title }}
          url: ${{ on.poll.outputs.link }}
          content: ${{ on.poll.outputs.content }}
          contentSnippet: ${{ on.poll.outputs.contentSnippet }}
        run: echo Liking $title $url $content $contentSnippet
