name: Test formatting and dedup

on:
  poll:
    url: https://jsonplaceholder.typicode.com/posts
    deduplicationKey: newId
    config:
      format: |
        item.newId = item.id
        item.title = item.title.substring(0,5)
        return item;

jobs:
  print:
    name: Test Print
    runs-on: ubuntu-latest
    steps:
      - name: Test Print
        env:
          id: ${{ on.poll.outputs.id }}
        run: echo Testing $id
